import { WooProduct } from "@/lib/woocommerce"

export const MOCK_PRODUCTS: WooProduct[] = [
  {
    id: 1,
    name: "Premium Brake Pad Set",
    slug: "premium-brake-pad-set",
    permalink: "/product/premium-brake-pad-set/",
    type: "simple",
    status: "publish",
    featured: true,
    sku: "BRK-001",
    price: "89.99",
    regular_price: "119.99",
    sale_price: "89.99",
    on_sale: true,
    stock_quantity: 45,
    stock_status: "instock",
    categories: [{ id: 1, name: "Brakes", slug: "brakes" }, { id: 101, name: "BMW", slug: "bmw-spare-parts" }],
    tags: [],
    images: [{ id: 1, src: "/brake-pads-automotive.jpg", alt: "Brake Pads" }],
    description:
      "High-performance brake pads designed for superior stopping power. Features ceramic compound for reduced dust and noise. Compatible with a wide range of vehicles.",
    short_description: "High-performance ceramic brake pads",
    attributes: [
      { id: 1, name: "Material", options: ["Ceramic Compound"] },
      { id: 2, name: "Position", options: ["Front"] },
      { id: 3, name: "Warranty", options: ["Limited Lifetime"] },
    ],
    meta_data: [],
    average_rating: "4.8",
    rating_count: 234,
  },
  {
    id: 2,
    name: "Oil Filter - High Performance",
    slug: "oil-filter-high-performance",
    permalink: "/product/oil-filter-high-performance/",
    type: "simple",
    status: "publish",
    featured: false,
    sku: "ENG-002",
    price: "24.99",
    regular_price: "24.99",
    sale_price: "",
    on_sale: false,
    stock_quantity: 120,
    stock_status: "instock",
    categories: [{ id: 2, name: "Engine Parts", slug: "engine-parts" }, { id: 101, name: "BMW", slug: "bmw-spare-parts" }, { id: 102, name: "Mercedes", slug: "mercedes-spare-parts" }],
    tags: [],
    images: [{ id: 2, src: "/oil-filter-automotive.jpg", alt: "Oil Filter" }],
    description:
      "Premium oil filter with synthetic fiber filtration media. Removes 99% of harmful contaminants. Easy installation with anti-drain back valve.",
    short_description: "Premium synthetic fiber oil filter",
    attributes: [
      { id: 1, name: "Type", options: ["Spin-On"] },
      { id: 2, name: "Material", options: ["Synthetic Fiber"] },
      { id: 3, name: "Warranty", options: ["1 Year"] },
    ],
    meta_data: [],
    average_rating: "4.9",
    rating_count: 567,
  },
  {
    id: 3,
    name: "LED Headlight Bulbs H11",
    slug: "led-headlight-bulbs-h11",
    permalink: "/product/led-headlight-bulbs-h11/",
    type: "simple",
    status: "publish",
    featured: false,
    sku: "LGT-003",
    price: "45.99",
    regular_price: "59.99",
    sale_price: "45.99",
    on_sale: true,
    stock_quantity: 78,
    stock_status: "instock",
    categories: [{ id: 3, name: "Lighting", slug: "lighting" }, { id: 101, name: "BMW", slug: "bmw-spare-parts" }, { id: 103, name: "Audi", slug: "audi-spare-parts" }],
    tags: [],
    images: [{ id: 3, src: "/led-headlight-bulbs.jpg", alt: "LED Headlight" }],
    description: "Ultra-bright LED headlight bulbs with 6000K white light. 300% brighter than halogen. Plug-and-play installation with built-in cooling fan.",
    short_description: "6000K ultra-bright LED bulbs",
    attributes: [
      { id: 1, name: "Lumens", options: ["12000"] },
      { id: 2, name: "Color Temp", options: ["6000K"] },
      { id: 3, name: "Warranty", options: ["2 Years"] },
    ],
    meta_data: [],
    average_rating: "4.7",
    rating_count: 189,
  },
  {
    id: 4,
    name: "Spark Plugs - Platinum",
    slug: "spark-plugs-platinum",
    permalink: "/product/spark-plugs-platinum/",
    type: "simple",
    status: "publish",
    featured: false,
    sku: "ENG-004",
    price: "32.99",
    regular_price: "32.99",
    sale_price: "",
    on_sale: false,
    stock_quantity: 200,
    stock_status: "instock",
    categories: [{ id: 2, name: "Engine Parts", slug: "engine-parts" }, { id: 101, name: "BMW", slug: "bmw-spare-parts" }],
    tags: [],
    images: [{ id: 4, src: "/spark-plugs-automotive.jpg", alt: "Spark Plugs" }],
    description: "Platinum-tipped spark plugs for improved fuel efficiency and smoother engine performance. Pre-gapped for easy installation. Set of 4.",
    short_description: "Platinum-tipped for improved efficiency",
    attributes: [
      { id: 1, name: "Material", options: ["Platinum"] },
      { id: 2, name: "Gap", options: ["0.044\""] },
      { id: 3, name: "Warranty", options: ["Limited Lifetime"] },
    ],
    meta_data: [],
    average_rating: "4.9",
    rating_count: 892,
  },
  {
    id: 5,
    name: "Air Filter - Performance",
    slug: "air-filter-performance",
    permalink: "/product/air-filter-performance/",
    type: "simple",
    status: "publish",
    featured: false,
    sku: "ENG-005",
    price: "54.99",
    regular_price: "54.99",
    sale_price: "",
    on_sale: false,
    stock_quantity: 50,
    stock_status: "instock",
    categories: [{ id: 2, name: "Engine Parts", slug: "engine-parts" }, { id: 102, name: "Mercedes", slug: "mercedes-spare-parts" }],
    tags: [],
    images: [{ id: 5, src: "/air-filter-automotive.jpg", alt: "Air Filter" }],
    description: "High-flow performance air filter.",
    short_description: "High-flow performance air filter",
    attributes: [],
    meta_data: [],
    average_rating: "4.6",
    rating_count: 345,
  },
  {
    id: 6,
    name: "Alternator - Remanufactured",
    slug: "alternator-remanufactured",
    permalink: "/product/alternator-remanufactured/",
    type: "simple",
    status: "publish",
    featured: false,
    sku: "ELC-006",
    price: "189.99",
    regular_price: "249.99",
    sale_price: "189.99",
    on_sale: true,
    stock_quantity: 15,
    stock_status: "instock",
    categories: [{ id: 4, name: "Electrical", slug: "electrical" }, { id: 101, name: "BMW", slug: "bmw-spare-parts" }],
    tags: [],
    images: [{ id: 6, src: "/alternator-automotive.jpg", alt: "Alternator" }],
    description: "Quality remanufactured alternator.",
    short_description: "Quality remanufactured alternator",
    attributes: [],
    meta_data: [],
    average_rating: "4.5",
    rating_count: 123,
  },
  {
    id: 7,
    name: "BMW Genuine Oil Filter",
    slug: "bmw-genuine-oil-filter",
    permalink: "/product/bmw-genuine-oil-filter/",
    type: "simple",
    status: "publish",
    featured: true,
    sku: "BMW-FIL-001",
    price: "18.99",
    regular_price: "22.99",
    sale_price: "18.99",
    on_sale: true,
    stock_quantity: 100,
    stock_status: "instock",
    categories: [{ id: 2, name: "Engine Parts", slug: "engine-parts" }, { id: 101, name: "BMW", slug: "bmw-spare-parts" }],
    tags: [],
    images: [{ id: 7, src: "/oil-filter-automotive.jpg", alt: "BMW Oil Filter" }],
    description: "Genuine BMW Oil Filter for various models.",
    short_description: "Genuine BMW Oil Filter for various models",
    attributes: [],
    meta_data: [],
    average_rating: "5.0",
    rating_count: 42,
  },
  // User requested missing product
  {
    id: 999,
    name: "Porsche Macan Carrier Charge Air Cooler Right 95B805594D D",
    slug: "porsche-macan-carrier-charge-air-cooler-right-95b805594d-d",
    permalink: "/product/porsche-macan-carrier-charge-air-cooler-right-95b805594d-d/",
    type: "simple",
    status: "publish",
    featured: false,
    sku: "POR-MAC-001",
    price: "450.00",
    regular_price: "450.00",
    sale_price: "",
    on_sale: false,
    stock_quantity: 5,
    stock_status: "instock",
    categories: [{ id: 5, name: "Porsche", slug: "porsche-spare-parts" }, { id: 6, name: "Cooling", slug: "cooling" }],
    tags: [],
    images: [{ id: 8, src: "/placeholder.svg", alt: "Porsche Macan Cooler" }],
    description: "Genuine Porsche Macan Carrier Charge Air Cooler Right. Part Number: 95B805594D D.",
    short_description: "Genuine Porsche Macan Carrier Charge Air Cooler",
    attributes: [
       { id: 1, name: "Position", options: ["Right"] },
       { id: 2, name: "Part Number", options: ["95B805594D D"] }
    ],
    meta_data: [],
    average_rating: "0",
    rating_count: 0,
  }
]
